"""Extract the monster poach map from the game's PoachItem sheet (LW-167 Living Poach).

Reads nxd/poachitem.en.nxd out of the English data pac, decodes it with FF16Tools, and
writes LivingWeapon/poach.json: one entry per monster species with the carcass-store Keys
and display names the runtime needs.

Ground truth (owner probe session 2026-08-12, LIVE_LEDGER row dated 2026-08-12):
- The sheet has 96 rows = 48 species x (common IsRare=0, rare IsRare=1).
- The sheet's species column (decoded as "IconId" by the generic layout) equals
  victim job byte - 95 (chocobo job 96 = species 1; gobbledygook job 101 = species 6;
  both live-confirmed by vanilla poaches).
- The Poacher's Den carcass store is u8[96] at 0x1411A7A1B + (Key - 1); the Den UI reads
  it live and the engine increments it at battle end.

Rerun after a game patch (the pac path comes from tools/lib/paths.py) and commit the diff;
the json is the runtime's single source for the map.

Usage: python tools/extract_poach_map.py
"""
import json
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.nxd import PAC, unpack, decode_nxd_to_sqlite
from lib.paths import ROOT

WORK = ROOT / "working" / "nxd_poachitem"
OUT = ROOT / "LivingWeapon" / "poach.json"


def main():
    WORK.mkdir(parents=True, exist_ok=True)
    nxd = unpack(PAC, "nxd/poachitem.en.nxd", WORK)
    db = decode_nxd_to_sqlite([nxd], WORK, "poachitem.sqlite")

    con = sqlite3.connect(str(db))
    cur = con.cursor()
    # Unknown8 = singular display name; the generic layout labels the species column IconId.
    rows = cur.execute(
        "SELECT Key, Unknown8, IconId, IsRare FROM [PoachItem-en] ORDER BY Key"
    ).fetchall()
    if len(rows) != 96:
        raise SystemExit(f"expected 96 PoachItem rows, got {len(rows)} -- sheet layout changed?")

    species = {}
    for key, name, spec, is_rare in rows:
        entry = species.setdefault(int(spec), {})
        slot = "rare" if is_rare else "common"
        if slot in entry:
            raise SystemExit(f"species {spec} has two {slot} rows -- sheet layout changed?")
        entry[slot] = {"key": int(key), "name": name}

    problems = [s for s, e in species.items() if set(e) != {"common", "rare"}]
    if problems:
        raise SystemExit(f"species missing a common/rare half: {problems}")

    out = {
        "_provenance": "generated by tools/extract_poach_map.py from nxd/poachitem.en.nxd; "
                       "species = victim job byte - 95; carcass store u8[96] at "
                       "0x1411A7A1B + (key - 1); see LIVE_LEDGER row 2026-08-12",
        "species": {str(s): species[s] for s in sorted(species)},
    }
    OUT.write_text(json.dumps(out, indent=1), encoding="utf-8")
    print(f"wrote {OUT} ({len(species)} species)")


if __name__ == "__main__":
    main()
