#!/usr/bin/env python
"""Bake data/items.json -> LivingWeapon/meta.json (id -> {name, wp, cat, formula, flavor}).

The Living Weapon C# runtime reads this to route growth (PA/MA/Speed by category +
formula), to label the card, and to anchor the in-card Kills counter to the right
weapon by its FLAVOR line. Regenerated by BuildLinked.ps1 / Publish.ps1 before each
build so the mod ships self-contained.

The flavor line is the STABLE part of a weapon's description (it doesn't change as the
blade levels up); the description block now leads with the Kills tier-progress meter
(moved 2026-07-06) with the flavor line right below it, so the runtime finds each
weapon's own counter by the nearest flavor on EITHER side of a "Kills: " hit --
reliable per-weapon, unlike anchoring to the name (which lives in a separate UI buffer
far from the description copy).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.categories import WEAPON_CATS
from lib.flavor import flavor_anchor   # same deterministic flavor() the descriptions are baked from
from lib.items import load_items
from lib.paths import ROOT

OUT = ROOT / "LivingWeapon" / "meta.json"

# LW-156: the signature passthrough, table-driven. One row per uniform runtime key: (key, kind)
# where kind "int" emits int(sig[key]) and "flag" emits literal True. Gating is TRUTHINESS
# (if sig.get(key)), exactly the semantics of the old hand-written branch per key: an explicit
# 0 or false is OMITTED from meta.json, same as an absent key. EMISSION ORDER IS THE TABLE
# ORDER and meta.json is proven byte-identical on regenerate, so append new keys at the END
# unless a diff is intended. Non-uniform keys (hpBelow, the forTurns/mounted stat compound,
# ricochetPct's default-50 rider) stay hand-written in main() where their special rules are.
_SIG_PASSTHROUGH = (
    ("puppeteerTurns", "int"),        # puppeteer (Galewind): dominate the struck enemy for N of its turns
    ("doomCountdownTo", "int"),       # doom-hasten aura (Eclipsebolt "Eagle Eye"): force enemy Doom to this
    ("ricochetRadius", "int"),        # ricochet aura (Stormarc "Arc Lightning"): chip to nearest foe (+pct rider in main)
    ("crippleTurns", "int"),          # maim (Huntress "Maim"): struck enemies lose reactions N turns
    ("grantCommandAbilityId", "int"), # command grant (Yoichi "Barrage" / Sanguine "Shadow Blade")
    ("larcenyTurns", "int"),          # larceny (Arcanum): steal the struck foe's holdable buff onto the wielder
    ("lifeSapOnKill", "flag"),        # life sap (Umbral "Life Sap"): a kill heals the wielder
    ("regenSplashRadius", "int"),     # wyrmblood (Dragon Rod): turn-edge regen splash to allies
    ("regenAuraRadius", "int"),       # renewal (Mending Staff): turn-edge regen aura to adjacent allies (Chebyshev)
    ("fontOnMove", "flag"),           # spiritual font (Wellspring): a moved turn restores HP/MP (runtime-written)
    ("raptureMove", "flag"),          # rapture (Rod of Faith): low-HP Master Teleportation window
    ("feignDeath", "flag"),           # feign death (Wrathblade): hold Reraise -> play dead -> animated auto-revive
    ("afterimage", "flag"),           # afterimage (Swiftedge): Speed ramps each turn, resets on a hit
    ("ultima", "flag"),               # ultima (Materia Blade): always-on HP%-scaled PA hold
    ("healBoostPct", "int"),          # benediction (Sanctus Staff): ally HP-rise boost on wielder action window
    ("antiCrystallize", "flag"),      # sanctuary (Staff of the Magi): hold fallen allies' crystal counter while the bearer lives
    ("instantCastRadius", "int"),     # choir (Warlock's Staff): adjacent allies cast magick instantly (Non-charge aura)
    ("braveOneUp", "flag"),           # Kobu (Kiyomori): raise wielder's current brave to a bolder struck foe's
    ("iai", "flag"),                  # Iai (Ame-no-Murakumo): opening-turn Speed hold, reverted after that turn
    ("mushin", "flag"),               # Mushin (Kiku-ichimonji): a full WAIT turn arms a one-hit PA boost
    ("bulwark", "flag"),              # Bulwark (Sunderer): a full WAIT turn plants the blade, barring the tile behind
    ("gunSlinger", "flag"),           # Gun Slinger (Blaster): roster off-hand twin + Dual Wield between battles
)

# Signature keys that legitimately do NOT pass through to meta.json: consumed by the analyze.py
# gates / the description bake (lib/flavor.py) or handled by the hand-written block in main().
_SIG_HANDLED_ELSEWHERE = {
    "abilityId", "slot", "atTier", "displayLabel",        # base entry fields (main)
    "hpBelow", "stat", "statBonus", "forTurns", "mounted", # compound stat-grant rules (main)
    "ricochetPct",                                         # ricochetRadius's default-50 rider (main)
    "sigName", "p3Desc", "note",                           # card text + curator prose, never runtime
}


def main():
    doc = load_items()
    meta = {}
    for it in doc["items"]:
        p = it.get("proposed", {}) or {}
        cat = p.get("categoryOverride") or it.get("category")
        if cat not in WEAPON_CATS:
            continue
        if it.get("noGrowth"):
            continue   # excluded from the Living Weapon + system (e.g. Materia Blade)
        name = it.get("name")
        if not name or name == "TBD":
            continue
        wp = p.get("wp") or (it.get("baseline", {}) or {}).get("wp") or 0
        formula = p.get("formula") if isinstance(p.get("formula"), int) else 1
        entry = {
            "name": name, "wp": int(wp), "cat": cat, "formula": int(formula),
            "flavor": flavor_anchor(it),
        }
        sig = it.get("signature")
        if sig:   # iconic tier-grant; emit only the fields the runtime uses (drop curator notes).
            # abilityId/slot are absent on a timed stat grant (e.g. Galewind's Speed +3) -> default them.
            entry["signature"] = {
                "abilityId": int(sig.get("abilityId", 0)), "slot": sig.get("slot", ""), "atTier": int(sig["atTier"]),
                "displayLabel": sig.get("displayLabel", ""),
            }
            if sig.get("hpBelow"):   # conditional HP-gate (e.g. Mortal Coil: Attack Boost while HP < 50%)
                entry["signature"]["hpBelow"] = int(sig["hpBelow"])
            if sig.get("forTurns") or sig.get("mounted"):   # flat stat grant (timed OR mount-gated)
                entry["signature"]["stat"] = sig.get("stat", "")
                entry["signature"]["statBonus"] = int(sig.get("statBonus", 0))
            if sig.get("forTurns"):  # timed stat grant (e.g. Galewind: Speed +3 for the first 3 turns)
                entry["signature"]["forTurns"] = int(sig["forTurns"])
            if sig.get("mounted"):   # mount-gated flat stat grant (Cavalier's Charge): Speed while riding a chocobo
                entry["signature"]["mounted"] = True
            for key, kind in _SIG_PASSTHROUGH:
                if not sig.get(key):
                    continue
                entry["signature"][key] = True if kind == "flag" else int(sig[key])
                if key == "ricochetRadius":   # the one paired rider: pct defaults 50, radius-gated
                    entry["signature"]["ricochetPct"] = int(sig.get("ricochetPct", 50))
            # LW-156 gate: a signature key neither the table nor the hand-written block above
            # knows is a FUTURE MECHANIC BEING SILENTLY DROPPED on its way to the runtime (the
            # C#-side MetaSchemaTests only catch the opposite direction, an emitted key with no
            # property). Fail the bake loud instead: add a _SIG_PASSTHROUGH row, or allowlist a
            # genuinely non-runtime key in _SIG_HANDLED_ELSEWHERE.
            unknown = set(sig) - {k for k, _ in _SIG_PASSTHROUGH} - _SIG_HANDLED_ELSEWHERE
            if unknown:
                sys.exit(f"FAIL: id{it['id']} ({name}) signature carries unhandled key(s) "
                         f"{sorted(unknown)}: not in _SIG_PASSTHROUGH, not allowlisted in "
                         f"_SIG_HANDLED_ELSEWHERE, so meta.json would silently drop them")
        meta[str(it["id"])] = entry
    OUT.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT} ({len(meta)} weapons)")


if __name__ == "__main__":
    main()
