#!/usr/bin/env python
"""Bake data/items.json -> LivingWeapon/meta.json (id -> {name, wp, cat, formula, flavor}).

The Living Weapon C# runtime reads this to route growth (PA/MA/Speed by category +
formula), to label the card, and to anchor the in-card Kills counter to the right
weapon by its FLAVOR line. Regenerated by BuildLinked.ps1 / Publish.ps1 before each
build so the mod ships self-contained.

The flavor line is the STABLE part of a weapon's description (it doesn't change as the
blade levels up), and it leads the description block that ends in the "Kills: 0" line,
so the runtime can find each weapon's own counter by the nearest flavor before a
"Kills: " -- reliable per-weapon, unlike anchoring to the name (which lives in a
separate UI buffer far from the description copy).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.categories import WEAPON_CATS
from lib.flavor import flavor_anchor   # same deterministic flavor() the descriptions are baked from
from lib.items import load_items
from lib.paths import ROOT

OUT = ROOT / "LivingWeapon" / "meta.json"


def main():
    doc = load_items()
    meta = {}
    for it in doc["items"]:
        p = it.get("proposed", {}) or {}
        cat = p.get("categoryOverride") or it.get("category")
        if cat not in WEAPON_CATS:
            continue
        if it.get("noGrowth"):
            continue   # excluded from the Living Weapon + system (e.g. Materia Blade)
        name = it.get("name")
        if not name or name == "TBD":
            continue
        wp = p.get("wp") or (it.get("baseline", {}) or {}).get("wp") or 0
        formula = p.get("formula") if isinstance(p.get("formula"), int) else 1
        entry = {
            "name": name, "wp": int(wp), "cat": cat, "formula": int(formula),
            "flavor": flavor_anchor(it),
        }
        sig = it.get("signature")
        if sig:   # iconic tier-grant; emit only the fields the runtime uses (drop curator notes).
            # abilityId/slot are absent on a timed stat grant (e.g. Galewind's Speed +3) -> default them.
            entry["signature"] = {
                "abilityId": int(sig.get("abilityId", 0)), "slot": sig.get("slot", ""), "atTier": int(sig["atTier"]),
                "displayLabel": sig.get("displayLabel", ""),
            }
            if sig.get("hpBelow"):   # conditional HP-gate (e.g. Mortal Coil: Attack Boost while HP < 50%)
                entry["signature"]["hpBelow"] = int(sig["hpBelow"])
            if sig.get("forTurns") or sig.get("mounted"):   # flat stat grant (timed OR mount-gated)
                entry["signature"]["stat"] = sig.get("stat", "")
                entry["signature"]["statBonus"] = int(sig.get("statBonus", 0))
            if sig.get("forTurns"):  # timed stat grant (e.g. Galewind: Speed +3 for the first 3 turns)
                entry["signature"]["forTurns"] = int(sig["forTurns"])
            if sig.get("mounted"):   # mount-gated flat stat grant (Cavalier's Charge): Speed while riding a chocobo
                entry["signature"]["mounted"] = True
            if sig.get("charmLockTurns"):  # charm-lock aura (Galewind): landed Charm unbreakable N turns
                entry["signature"]["charmLockTurns"] = int(sig["charmLockTurns"])
            if sig.get("puppeteerTurns"):  # puppeteer (Galewind): dominate the struck enemy for N of its turns (replaces charm-lock)
                entry["signature"]["puppeteerTurns"] = int(sig["puppeteerTurns"])
            if sig.get("doomCountdownTo"):  # doom-hasten aura (Eclipsebolt "Eagle Eye"): force enemy Doom to this
                entry["signature"]["doomCountdownTo"] = int(sig["doomCountdownTo"])
            if sig.get("ricochetRadius"):  # ricochet aura (Stormarc "Arc Lightning"): chip to nearest foe
                entry["signature"]["ricochetRadius"] = int(sig["ricochetRadius"])
                entry["signature"]["ricochetPct"] = int(sig.get("ricochetPct", 50))
            if sig.get("crippleTurns"):  # maim (Huntress "Maim"): struck enemies lose reactions N turns
                entry["signature"]["crippleTurns"] = int(sig["crippleTurns"])
            if sig.get("grantCommandAbilityId"):  # command grant (Yoichi "Barrage" / Sanguine "Shadow Blade")
                entry["signature"]["grantCommandAbilityId"] = int(sig["grantCommandAbilityId"])
            if sig.get("larcenyTurns"):  # larceny (Arcanum): steal the struck foe's holdable buff onto the wielder
                entry["signature"]["larcenyTurns"] = int(sig["larcenyTurns"])
            if sig.get("lifeSapOnKill"):  # life sap (Umbral "Life Sap"): a kill heals the wielder
                entry["signature"]["lifeSapOnKill"] = True
            if sig.get("regenSplashRadius"):  # wyrmblood (Dragon Rod): turn-edge regen splash to allies
                entry["signature"]["regenSplashRadius"] = int(sig["regenSplashRadius"])
            if sig.get("regenAuraRadius"):  # renewal (Mending Staff): turn-edge regen aura to adjacent allies (Chebyshev)
                entry["signature"]["regenAuraRadius"] = int(sig["regenAuraRadius"])
            if sig.get("fontOnMove"):  # spiritual font (Wellspring): a moved turn restores HP/MP (runtime-written)
                entry["signature"]["fontOnMove"] = True
            if sig.get("raptureMove"):  # rapture (Rod of Faith): low-HP Master Teleportation window
                entry["signature"]["raptureMove"] = True
            if sig.get("feignDeath"):  # feign death (Wrathblade): hold Reraise -> play dead -> animated auto-revive
                entry["signature"]["feignDeath"] = True
            if sig.get("afterimage"):  # afterimage (Swiftedge): Speed ramps each turn, resets on a hit
                entry["signature"]["afterimage"] = True
            if sig.get("ultima"):   # ultima (Materia Blade): always-on HP%-scaled PA hold
                entry["signature"]["ultima"] = True
            if sig.get("healBoostPct"):  # benediction (Sanctus Staff): ally HP-rise boost on wielder action window
                entry["signature"]["healBoostPct"] = int(sig["healBoostPct"])
            if sig.get("antiCrystallize"):  # sanctuary (Staff of the Magi): hold fallen allies' crystal counter while the bearer lives
                entry["signature"]["antiCrystallize"] = True
            if sig.get("instantCastRadius"):  # choir (Warlock's Staff): adjacent allies cast magick instantly (Non-charge aura)
                entry["signature"]["instantCastRadius"] = int(sig["instantCastRadius"])
            if sig.get("braveOneUp"):  # Kobu (Kiyomori): on a melee hit the wielder lands, if struck foe's CURRENT brave (band +0x0F) exceeds the wielder's, raise wielder's current brave to match
                entry["signature"]["braveOneUp"] = True
            if sig.get("iai"):  # Iai (Ame-no-Murakumo): at battle start, hold the wielder's Speed above the field so it takes the opening turn, then revert after that turn
                entry["signature"]["iai"] = True
            if sig.get("gunSlinger"):  # Gun Slinger (Blaster): roster off-hand twin + Dual Wield between battles
                entry["signature"]["gunSlinger"] = True
        meta[str(it["id"])] = entry
    OUT.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT} ({len(meta)} weapons)")


if __name__ == "__main__":
    main()
