#!/usr/bin/env python
"""Bake data/items.json -> LivingWeapon/meta.json (id -> {name, wp, cat, formula, flavor}).

The Living Weapon C# runtime reads this to route growth (PA/MA/Speed by category +
formula), to label the card, and to anchor the in-card Kills counter to the right
weapon by its FLAVOR line. Regenerated by BuildLinked.ps1 / Publish.ps1 before each
build so the mod ships self-contained.

The flavor line is the STABLE part of a weapon's description (it doesn't change as the
blade levels up), and it sits in the same description block right before "Kills 0000",
so the runtime can find each weapon's own counter by the nearest flavor before a
"Kills " -- reliable per-weapon, unlike anchoring to the name (which lives in a
separate UI buffer far from the description copy).
"""
import json
from pathlib import Path
from patch_names import flavor   # same deterministic flavor() the descriptions are baked from

ROOT = Path(__file__).resolve().parent.parent
ITEMS = ROOT / "data" / "items.json"
OUT = ROOT / "LivingWeapon" / "meta.json"

WEAPON_CATS = {"Knife", "NinjaBlade", "Sword", "KnightSword", "Katana", "Axe", "Rod", "Staff",
               "Flail", "Gun", "Crossbow", "Bow", "Instrument", "Book", "Polearm", "Pole", "Bag", "Cloth"}


def flavor_anchor(it):
    """The exact flavor line that leads this weapon's rendered description -- mirrors
    patch_names: a custom `desc` uses its first line; otherwise flavorOverride or flavor()."""
    custom = it.get("desc")
    if custom:
        return custom.split("\n", 1)[0]
    return it.get("flavorOverride") or flavor(it)


def main():
    doc = json.loads(ITEMS.read_text(encoding="utf-8"))
    meta = {}
    for it in doc["items"]:
        p = it.get("proposed", {}) or {}
        cat = p.get("categoryOverride") or it.get("category")
        if cat not in WEAPON_CATS:
            continue
        name = it.get("name")
        if not name or name == "TBD":
            continue
        wp = p.get("wp") or (it.get("baseline", {}) or {}).get("wp") or 0
        formula = p.get("formula") if isinstance(p.get("formula"), int) else 1
        meta[str(it["id"])] = {
            "name": name, "wp": int(wp), "cat": cat, "formula": int(formula),
            "flavor": flavor_anchor(it),
        }
    OUT.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT} ({len(meta)} weapons)")


if __name__ == "__main__":
    main()
