#!/usr/bin/env python
"""
Generate the modloader item tables from data/items.json (single source of truth).

Emits (under out/):
  - ItemWeaponData.xml : sparse override, COMPLETE per item we touch (so load-order
    yields a clean winner vs other item mods, never a hybrid -- see docs/DESIGN.md).
  - names.json         : id -> new name/description, the handoff for the item.en.nxd
    rename patch (NXD round-trip mechanism pending the reference workflow).

Usage: python tools/generate.py [data/items.json] [out_dir]
"""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ITEMS = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "data" / "items.json"
# Weapon XML goes straight into the deployable mod tree; names.json is a build handoff.
MOD_TABLES = ROOT / "mod" / "FFTIVC" / "tables" / "enhanced"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "out"

WEAPON_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tools/generate.py from data/items.json — DO NOT EDIT BY HAND.
  FFT:IVC Item Overhaul. Complete per-item override (all weapon fields set) so load
  order produces a clean winner against other item mods. Load AFTER other item mods.
-->
<ItemWeaponTable>
  <Version>1</Version>
  <Entries>
"""
WEAPON_FOOTER = "  </Entries>\n</ItemWeaponTable>\n"

WEAPON_CATEGORIES = {"Knife", "NinjaBlade", "Sword", "KnightSword", "Katana", "Axe",
                     "Rod", "Staff", "Flail", "Gun", "Crossbow", "Bow", "Instrument",
                     "Book", "Polearm", "Pole", "Bag", "Cloth"}


def weapon_entry(it):
    s = it["proposed"]
    name = it.get("name") if it.get("name") not in (None, "TBD") else it["vanillaName"]
    comment = f"{name}" + (f" (was {it['vanillaName']})" if name != it["vanillaName"] else "")
    return (
        f"    <ItemWeapon>\n"
        f"      <Id>{it['id']}</Id> <!-- {comment} -->\n"
        f"      <Range>{s.get('range', 1)}</Range>\n"
        f"      <AttackFlags>{s.get('attackFlags', 'Striking')}</AttackFlags>\n"
        f"      <Formula>{s.get('formula', 1)}</Formula>\n"
        f"      <Unused_0x03>255</Unused_0x03>\n"
        f"      <Power>{s['wp']}</Power>\n"
        f"      <Evasion>{s['evade']}</Evasion>\n"
        f"      <Elements>{s.get('element', 'None')}</Elements>\n"
        f"      <OptionsAbilityId>{s.get('onHitAbilityId', 0)}</OptionsAbilityId>\n"
        f"    </ItemWeapon>\n"
    )


def main():
    doc = json.loads(ITEMS.read_text(encoding="utf-8"))
    items = sorted(doc["items"], key=lambda x: x["id"])
    OUT.mkdir(parents=True, exist_ok=True)
    MOD_TABLES.mkdir(parents=True, exist_ok=True)

    weapons = [it for it in items if it["category"] in WEAPON_CATEGORIES]
    xml = WEAPON_HEADER + "".join(weapon_entry(it) for it in weapons) + WEAPON_FOOTER
    (MOD_TABLES / "ItemWeaponData.xml").write_text(xml, encoding="utf-8")

    names = {str(it["id"]): {"name": it.get("name"), "vanillaName": it["vanillaName"]}
             for it in items if it.get("name") not in (None, "TBD")}
    (OUT / "names.json").write_text(json.dumps(names, indent=2, ensure_ascii=False), encoding="utf-8")

    placeholder = sum(1 for it in items if it.get("name") in (None, "TBD"))
    print(f"Wrote {MOD_TABLES / 'ItemWeaponData.xml'} ({len(weapons)} weapons)")
    print(f"Wrote {OUT / 'names.json'} ({len(names)} renames; {placeholder} still TBD)")
    if placeholder:
        print(f"NOTE: {placeholder} items have placeholder names (design workflow pending).")


if __name__ == "__main__":
    main()
